image: docker:latest

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - Docker-test

deploy-test:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - Docker-test
  script:
    - upgrade --environment "Production" --new-image "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --start-before-stopping --stack PHPM-preprod --service PHPM-preprod-php
    - upgrade --environment "Production" --new-image "r.bde-insa-lyon.fr/bdeinsalyon/phpm-nginx:latest" --stack PHPM-preprod --service PHPM-preprod-nginx
